### ISSUE TITLE
Tiled Ingest needs to add specs somehow

### ISSUE THREAD

**Issue by dylanmcreynolds** [mlexchange/mlex_tiled_ingest#3]
This arises from the belief (perhaps incorrect?) that the spec would be useful for letting consumers of the dataset know where to find data.

Here is the thinking.

We are going to be registering tomocraphic reconstructions that we get from Diamond. These are like likely nexus files. If we're reading the tiled code correctly, then if they has `.nxs` file extensions, they'll be recognized as nexus and the hdf5 adapter will be used.

However, knowing that it's hdf5 does not tell the client all that they'll need to know. You could parse the file to glean whether it's an NXtomo file and therefore figure out where in the file to get the data. We had thought "spec" might be the appropriate/fastest way to advertize to clients what kind of data they have. 

If we do that, then I think we'll have to define out own adapter, and register that with the tiled server.

How would tiled (both in the ingestion code here and at read time) know that a particular file was "NXtomo" and not just "A Nexus file)?

**Comment by danielballan** [comment]
I think this is correct interpretation of what specs are intended for.

You may not need a custom Adapter, however; it may be good enough to use the `HDF5Adapter` for reading the data.

I think that whatever is registering the files (e.g. the directory walker) should peek into anything HDF5 and investigate, "Is the _layout_ of this HDF5 structure something I recognize?" If so, I would suggest giving two specs, `["NXtomo", "NX"]`. This communicates to the client, "If you have a custom integration for `NXtomo` specifically, use it. If you don't but you know nexus generally (`NX`) use that."

On the client side, you might want a [custom class](https://blueskyproject.io/tiled/how-to/custom-clients.html) to representing these types of nodes. Likewise, a UI might do something with this information.

**Comment by dylanmcreynolds** [comment]
@danielballan , my next challenge is to figure out to add specs at `register` time. When I call [register](https://github.com/bluesky/tiled/blob/fcf01467ecc81c019b084f4d8306629639c5af01/tiled/catalog/register.py#L134) with the following, it doesn't result in any specs being saved.

```
specs=[{"name": "a_nexus", "version": "a_version"}]
```

**Comment by danielballan** [comment]
Did https://github.com/bluesky/tiled/pull/661 and related discussion resolve this?

**Comment by dylanmcreynolds** [comment]
Fixed in #4
